#!/bin/bash

KERNEL=$1
OUTPUT=${2:-/data}

if [ -z "$KERNEL" ]; then
    2> echo "Please supply kernel to build"
    exit 1
fi

extract_kernel_version() {
    local EXTERNSION
    local FILENAME

    FILENAME="`basename $1`"
    EXTENSION=`echo $FILENAME | grep -o -E '\.tar\.[a-z]+$'`

    basename -s $EXTENSION $FILENAME
}

if [[ "$KERNEL" = "http"* ]]; then
    URL="$KERNEL"
    KERNEL=$(extract_kernel_version "${KERNEL}")
else
    MAJOR=`echo $KERNEL | grep -o -E '[0-9]+' | head -n1`
    URL="https://cdn.kernel.org/pub/linux/kernel/v$MAJOR.x/$KERNEL.tar.gz"
fi
mkdir -p $OUTPUT || true
cd $OUTPUT

extract_kernel() {
    local FILENAME
    FILENAME=$(basename "$URL")

    if [ ! -f "${OUTPUT}/${FILENAME}" ]; then
        echo "Downloading kernel from $URL"
        echo "curl -L $URL > ${OUTPUT}/$FILENAME"
        curl -L "$URL" > ${OUTPUT}/$FILENAME
    fi

    tar -C "${OUTPUT}" -xf "${FILENAME}"
}

ensure_kernel() {
    if [ ! -d "${OUTPUT}/${KERNEL}" ]; then
        extract_kernel
    fi

    ln -s "${OUTPUT}/${KERNEL}" "/usr/src/${KERNEL}"
}

ensure_kernel

apt-get -y update
apt -y install linux-image-amd64
cd ${OUTPUT}/${KERNEL}

OLDCONF=`ls /boot/config-* | sort | tail -n1`

cp "${OLDCONF}" .config

# Disable debug builds
./scripts/config --disable CONFIG_DEBUG_INFO
./scripts/config --enable CONFIG_DEBUG_INFO_NONE
./scripts/config --disable DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT
./scripts/config --disable DEBUG_INFO_DWARF4
./scripts/config --disable DEBUG_INFO_DWARF5

# Disable kernel signing
sed -ri '/CONFIG_SYSTEM_TRUSTED_KEYS/s/=.+/=""/g' .config

# Enable I2C_HID
# https://elrepo.org/bugs/view.php?id=1123&nbn=2
./scripts/config --set-val CONFIG_I2C_HID_ACPI m

# Enable vGPU module
./scripts/config --set-val CONFIG_VFIO_MDEV_DEVICE m

# Fix call to python3 
if [ ! -x `which python3` ]; then
    ln -s `which python` /usr/bin/python3
fi

make olddefconfig
make -j`nproc` bindeb-pkg
